import type { NextPage } from 'next';
import Head from 'next/head';
import { Box, HStack } from '@chakra-ui/react';
import Layout from '../components/Layout';
import AddColumnForm from '../components/AddColumnForm';
import ColumnDisplay from '../components/ColumnDisplay';
import useColumn from '../hooks/useColumn';
import { Droppable, Draggable } from 'react-beautiful-dnd';

const Home: NextPage = () => {
  const { getOrderedColumns } = useColumn();

  return (
    <Layout>
      <Box>
        <Head>
          <title>Todo App Framer</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Droppable droppableId='main' direction="horizontal">
          {provided => (
            <HStack 
              {...provided.droppableProps}
              ref={provided.innerRef}
              align={"flex-start"}
            >
              {getOrderedColumns().map(({ column, todosList }, index) => (
                <Draggable draggableId={column.id} index={index}>
                  {provided => (
                    <Box 
                      {...provided.draggableProps}
                      {...provided.dragHandleProps}
                      ref={provided.innerRef}
                    >
                      <ColumnDisplay column={column} todos={todosList} /> 
                    </Box>
                  )}
                </Draggable>
              ))}
              {provided.placeholder}
              <AddColumnForm />
            </HStack>
          )}
        </Droppable>        
      </Box>
    </Layout>
  );
}

export default Home;