import type { NextPage } from 'next';
import Head from 'next/head';
import { 
  Button,
  Container, 
  Box, 
  Heading, 
  Stack, 
  Input, 
  Flex,
  Spacer,
  Switch,
  useColorMode, 
  useColorModeValue, 
} from '@chakra-ui/react';
import Task from '../components/Task';
import Todo from '../model/Todo';
import useTodo from '../hooks/useTodo';

const Home: NextPage = () => {
  const {
    todos,
    handleAdd,
    handleComplete,
    handleRemove
  } = useTodo();
  const { toggleColorMode } = useColorMode();
  const boxColorBox = useColorModeValue('gray.200', 'gray.700');

  return (
    <Container>
      <Head>
        <title>Todo App Framer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex>
        <Heading p="1rem">Todo-app</Heading>
        <Spacer />
        <Switch p="2rem" id='color-mode' onChange={toggleColorMode} />
      </Flex>
      <Box>
        <Flex spacing={4}>
          <Input mb="1rem" placeholder='Insert text' />
          <Button colorScheme={'blue'} onClick={_ => handleAdd()}>
            Agregar
          </Button>
        </Flex>
        <Box p="1rem" bg={boxColorBox} rounded="xl">
          <Stack spacing={3}>
            {todos.map((item: Todo) => 
              <Task 
                key={item.id}
                todo={item} 
                handleComplete={handleComplete} 
                handleRemove={handleRemove} 
              />
            )}
          </Stack>
        </Box>
      </Box>      
    </Container>
  );
}

export default Home;