import type { NextPage } from 'next';
import Head from 'next/head';
import { Box, HStack } from '@chakra-ui/react';
import AddTaskForm from '../components/AddTaskForm';
import Layout from '../components/Layout';

const Home: NextPage = () => (
  <Layout>
    <Box>
      <Head>
        <title>Todo App Framer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AddTaskForm />
      <HStack align={"flex-start"}>
        
      </HStack>        
    </Box>
  </Layout>
);

export default Home;